apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ethereum-snapshotter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: parity-config
data:
  parity.toml: |
    [parity]
    mode = "active"
    base_path = "/data"
    [network]
    warp = false
    [rpc]
    interface = "all"
    [footprint]
    db_compaction = "hdd"
    tracing = "off"
